version: "2"
services:

    web:
        image: node:12.18.3

        working_dir: "/app"
        tty: true
        stdin_open: true
        command: "npm start"

        volumes:
            - $PWD/:/app
        ports:
            - "3000:3000"  # for web app
            - "9229:9229"  # for node debugger
        links:
            - redis
            - postgres
        environment:
            ROOT_DIR: "/app"
            NODE_ENV: "development"
            NODE_PATH: "/usr/local/lib/node_modules/"

    redis:
        image: redis
        ports:
            - "6379:6379"

    postgres:
        image: timescale/timescaledb:latest-pg14
        volumes:
            - "db-data:/var/lib/postgresql/data/pgdata"
            - $PWD/src/lib/db/init/schema.sql:/docker-entrypoint-initdb.d/schema.sql
        ports:
            - "5432:5432"
        environment:
            PGDATA: "/var/lib/postgresql/data/pgdata"
            POSTGRES_USER: "pguser"
            POSTGRES_PASSWORD: "password"



volumes:
  db-data:
